# Generated by Django 4.2.29 on 2026-04-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_edit_collection',
            field=models.BooleanField(db_index=True, default=False, help_text='Create/edit collections on behalf of any staff member in this vendor.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_export_data',
            field=models.BooleanField(db_index=True, default=False, help_text='Download CSV exports.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_view_all_collections',
            field=models.BooleanField(db_index=True, default=False, help_text='See all collections for this vendor (not only own).'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_view_reports',
            field=models.BooleanField(db_index=True, default=False, help_text='Access analytics and staff breakdown reports.'),
        ),
    ]
