# Generated by Django 4.2.29 on 2026-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_categories',
            field=models.BooleanField(db_index=True, default=False, help_text='Add, edit, and delete product categories (manage categories modal).'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_manage_products',
            field=models.BooleanField(db_index=True, default=False, help_text='Add, edit, and delete products for this vendor.'),
        ),
    ]
