# Generated by Django 5.2.12 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_product_category_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
