# Generated by Django 5.2.12 on 2026-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_customers',
            field=models.BooleanField(db_index=True, default=False, help_text='Add and edit customers (subject to customer visibility rules for this vendor).'),
        ),
    ]
