# Generated by Django 4.2.29 on 2026-04-02 11:05

from django.db import migrations, models
import django.db.models.deletion


def backfill_customer_staff_from_collections(apps, schema_editor):
    """
    Set customer.staff when a single staff member has all collections for that customer.
    Leave null when multiple staff collected for the same customer (vendor pool).
    """
    Customer = apps.get_model("customers", "Customer")
    Collection = apps.get_model("collections", "Collection")
    for customer in Customer.objects.filter(staff__isnull=True).iterator():
        staff_ids = list(
            Collection.objects.filter(customer_id=customer.pk)
            .values_list("staff_id", flat=True)
            .distinct()
        )
        if len(staff_ids) == 1 and staff_ids[0] is not None:
            customer.staff_id = staff_ids[0]
            customer.save(update_fields=["staff_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_permissions'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='staff.staff'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['vendor', 'staff'], name='idx_customer_vendor_staff'),
        ),
        migrations.RunPython(
            code=backfill_customer_staff_from_collections,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
