# Generated by Django 5.2.12 on 2026-04-02 11:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_day',
            field=models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
