# Generated by Django 5.2.12 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_vendor_phone',
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='uniq_customer_vendor_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor', 'phone'), name='uniq_customer_vendor_phone_active'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor', 'customer_code'), name='uniq_customer_vendor_code_active'),
        ),
    ]
