# Generated by Django 4.2.29 on 2026-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
