# Generated by Django 4.2.29 on 2026-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='staff_see_all_customers',
            field=models.BooleanField(db_index=True, default=False, help_text='When enabled, all staff in this vendor see every customer. When disabled, each staff member only sees customers assigned to them.'),
        ),
    ]
