# Generated by Django 4.2.29 on 2026-04-02 09:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('customers', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('day_number', models.PositiveIntegerField()),
                ('week_number', models.PositiveIntegerField(db_index=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='customers.customer')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='staff.staff')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'date'], name='idx_coll_vendor_date'), models.Index(fields=['vendor', 'staff', 'date'], name='idx_coll_vendor_staff_date'), models.Index(fields=['vendor', 'customer', 'date'], name='idx_coll_vendor_customer_date'), models.Index(fields=['vendor', 'week_number'], name='idx_coll_vendor_week')],
            },
        ),
    ]
