# Generated by Django 5.2.12 on 2026-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
