# Generated by Django 5.2.12 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_loan_day_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
