# Generated by Django 5.2.12 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
        ('vendors', '0002_vendor_staff_customer_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='uniq_productcategory_vendor_name',
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('vendor', 'name'), name='uniq_productcategory_vendor_name_active'),
        ),
    ]
